
const modals = [{
  modalId: 'con-1',
  name: 'PerspectiveWild',
  desc: "This is a react project that showcase the different types of animals both wild and domesticated. The project aims to shade light on the need to preserved the different species of animals and at the same time share facts curated for specific animals species. ",
  order: 'order--one',
  imageOneDesktop: './images/Card-images/SnapshootPortfolioDesktop1.png',
  skillSet: ['React', 'Jest', 'Thunk', 'bootstrap', 'redux'],
  jobProfile: ['FREELANCER', 'Front-End Dev', 2022],
  liveDemo:'https://6262b89a578849338355be2c--benevolent-peony-90404f.netlify.app/',
  gitHub: 'https://github.com/daudi13/seafood',
  API: 'https://zoo-animal-api.herokuapp.com/',
},
{
  modalId: 'con-2',
  name: 'Space-traveller',
  desc: "This is a dummy website for a commercial space company that sends people and satellites on space missions and users can book their missions on the site. This project uses the SpaceX Api to retrieve data that allows a user to interact with the different UI component in the app.",
  order: 'order--two',
  imageOneDesktop: './images/Card-images/SnapshootPortfolioDesktop2.png',
  skillSet: ['React', 'logger', 'thunk', 'redux', 'JEST'],
  jobProfile: ['FREELANCE', 'Front-End Dev', 2022],
  liveDemo:'https://space-traveller.herokuapp.com/',
  gitHub: 'https://github.com/daudi13/space-travel',
  API: 'https://zoo-animal-api.herokuapp.com/',
},
{
  modalId: 'con-3',
  name: 'Taste Jamaica',
  desc: "This project is a collaborative project made by me and @ahangarha. The project uses API to display various Jamaican dishes and it enables a user to like and leave a comment too ",
  order: 'order--one',
  imageOneDesktop: './images/Card-images/SnapshootPortfolioDesktop3.png',
  skillSet: ['Form-validation', 'APIs', 'javaScript', 'Jest'],
  jobProfile: ['FREELANCE', 'FrontEnd Dev', 2022],
  liveDemo:'https://ahangarha.github.io/JavaScript-Capstone/',
  gitHub: 'https://github.com/daudi13/JavaScript-Capstone',
  API: 'https://zoo-animal-api.herokuapp.com/',
},
{
  modalId: 'con-4',
  name: 'GRGF Festival',
  desc: " This is a version of an Imaginary website for a gaming festival I developed as part of my capstone project for the Microverse program module 1. The website is for an upcoming gaming festival for Gamers Rising, an extreme gaming gaming company that is having their first event in Africa here in Kenya. ",
  order: 'order--two',
  imageOneDesktop: './images/Card-images/SnapshootPortfolioDesktop4.png',
  skillSet: ['html', 'css', 'javaScript'],
  jobProfile: ['FREELANCE', 'FrontEnd Dev', 2020],
  liveDemo:'http://grgf.vercel.app/',
  gitHub: 'https://github.com/daudi13/space-travel',
  API: 'https://github.com/daudi13/grgf',
  }];

export default modals;